import axios from "axios"; const api = axios.create({ baseURL: "/api" }); export interface LibraryStats { total_liked: number; total_artists: number; total_albums: number; with_audio_features: number; by_review_status: Record<string, number>; oldest_liked_at: string | null; newest_liked_at: string | null; } export interface QueueTrack { track_id: string; name: string; primary_artist_name: string; artist_names: string; album_name: string; album_image: string | null; album_type: string | null; release_date: string | null; liked_at: string; review_status: string; review_notes: string | null; duration_ms: number; popularity: number | null; preview_url: string | null; spotify_url: string | null; explicit: number; energy: number | null; valence: number | null; tempo: number | null; danceability: number | null; acousticness: number | null; instrumentalness: number | null; play_count: number | null; total_minutes: number | null; skip_rate_pct: number | null; last_played_at: string | null; days_since_played: number | null; } export interface QueueStats { total: number; unreviewed: number; reviewed: number; progress_pct: number; } export interface ImportResult { status: string; counts: { found: number; new: number; updated: number; errors: number }; } export const getAuthStatus = () => api.get("/auth/status").then(r => r.data); export const getStats = () => api.get("/library/stats").then(r => r.data); export const getLikedSongs = (page = 1, pageSize = 50, status?: string) => api.get("/library/liked-songs", { params: { page, page_size: pageSize, status } }).then(r => r.data); export const importLikedSongs = (incremental = true) => api.post("/import/liked-songs", { incremental }).then(r => r.data); export const importAudioFeatures = () => api.post("/import/audio-features").then(r => r.data); export const getImportHistory = () => api.get("/import/history").then(r => r.data); export const getReviewQueue = (limit = 20) => api.get("/review/queue", { params: { limit } }).then(r => r.data); export const submitDecision = (track_id: string, status: string, notes?: string) => api.post("/review/decision", { track_id, status, notes }).then(r => r.data); export const undoLastDecision = () => api.post("/review/undo").then(r => r.data); export const getReviewStats = () => api.get("/review/stats").then(r => r.data);

export interface DiscoveryTrack { track_id: string; name: string; artist: string; play_count?: number; total_minutes?: number; recent_plays?: number; prior_plays?: number; delta?: number; last_played_at?: string; days_since_played?: number; }
export interface TrendingArtist { artist: string; recent_plays: number; prior_plays: number; delta: number; }
export interface DiscoveryOverview { available: boolean; unplaylisted_high_plays?: DiscoveryTrack[]; trending_tracks?: DiscoveryTrack[]; trending_artists?: TrendingArtist[]; forgotten_favourites?: DiscoveryTrack[]; }
export const getDiscoveryOverview = () => api.get("/discovery/overview").then(r => r.data);
export const importPlaylists = () => api.post("/import/playlists").then(r => r.data);
export const createPlaylist = (name: string, track_ids: string[], description?: string) =>
  api.post("/playlists/create", { name, track_ids, description }).then(r => r.data);
